### ISSUE TITLE
Unsession Proposal: This is Your Brain on Programming

### ISSUE THREAD

**Issue by wilwade** [strangeloop/StrangeLoop2016#3]
Hosted by : Wil Wade (@WilWade)
Description: How well do you understand the primary tool in programming: your brain? Join an introductory exploration of flow state, mental models, and burnout.
Interest: @

**Comment by jpivarski** [comment]
+1  I'd go to that. I've been an informal cognitive psychologist, analyzing my own work patterns, ever since I started ten years ago. It would be interesting to hear what other programmers (or even professional psychologists) have discovered about optimizing programmer throughput.

**Comment by wilwade** [comment]
Closing as the wiki editing is working.
